# Generated by Django 5.2 on 2025-05-07 13:35

import phonenumbers
from django.db import migrations


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        phone_number = flat.owners_phonenumber 
        parsed_number = phonenumbers.parse(phone_number, "RU")
        if phonenumbers.is_valid_number(parsed_number): 
            flat.owner_pure_phone = phonenumbers.format_number(
                parsed_number, phonenumbers.PhoneNumberFormat.E164
            )
        else:
            flat.owner_pure_phone = None
        flat.save() 


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers),
    ]
