# Generated by Django 5.2 on 2025-05-07 13:55

from django.db import migrations


def transfer_ownership_information(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.iterator():
        Owner.objects.get_or_create(
            name = flat.owner,
            phonenumber = flat.owners_phonenumber,
            pure_phone = flat.owner_pure_phone,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(transfer_ownership_information),
    ]
