# Generated by Django 5.2 on 2025-05-07 14:29

from django.db import migrations


def linking_apartments_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.iterator():
        owner = Owner.objects.filter(pure_phone=flat.owner_pure_phone).first() 
        if owner:
            owner.owned_apartments.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20250507_1655'),
    ]

    operations = [
        migrations.RunPython(linking_apartments_owners),
    ]
