# Generated by Django 5.2 on 2025-05-07 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20250507_1729'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='flat',
            constraint=models.UniqueConstraint(fields=('owner', 'owners_phonenumber'), name='unique_owner'),
        ),
    ]
