# Generated by Django 5.2 on 2025-05-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_flat_unique_owner'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='flat',
            name='unique_owner',
        ),
    ]
