# Generated by Django 5.2 on 2025-05-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_remove_flat_unique_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owned_apartments',
            new_name='flats',
        ),
    ]
